### ISSUE TITLE
【求问，急】报错找不到data/**.txt文件路径

### ISSUE THREAD

**Issue by pikozizi** [hzy46/Char-RNN-TensorFlow#18]
如题，报错找不到data/**.txt文件路径，怎么解决

**Comment by pikozizi** [comment]
Traceback (most recent call last):
  File "/home/piko/venv/Char-RNN-TensorFlow-master/Char-RNN-TensorFlow-master/train.py", line 56, in <module>
    tf.app.run()
  File "/home/piko/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/piko/venv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/piko/venv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/piko/venv/Char-RNN-TensorFlow-master/Char-RNN-TensorFlow-master/train.py", line 29, in main
    with codecs.open(FLAGS.input_file, encoding='utf-8') as f:
  File "/home/piko/venv/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'data/novel.txt'

**Comment by pikozizi** [comment]
Traceback (most recent call last):
  File "/home/piko/venv/Char-RNN-TensorFlow-master/Char-RNN-TensorFlow-master/train.py", line 56, in <module>
    tf.app.run()
  File "/home/piko/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/piko/venv/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/piko/venv/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/piko/venv/Char-RNN-TensorFlow-master/Char-RNN-TensorFlow-master/train.py", line 29, in main
    with codecs.open(FLAGS.input_file, encoding='utf-8') as f:
  File "/home/piko/venv/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'data/poetry.txt'
