### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by ilioner** [hzy46/Char-RNN-TensorFlow#2]
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 46, in main
    embedding_size=FLAGS.embedding_size
  File "/Volumes/Files/WorkFile/Demo/Char-RNN-TensorFlow/model.py", line 40, in __init__
    self.build_lstm()
  File "/Volumes/Files/WorkFile/Demo/Char-RNN-TensorFlow/model.py", line 79, in build_lstm
    seq_output = tf.concat(self.lstm_outputs, 1)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/array_ops.py", line 331, in concat
    dtype=dtypes.int32).get_shape(
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 510, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("lstm/RNN/transpose:0", shape=(32, 26, 128), dtype=float32)'

**Comment by hzy46** [comment]
确认版本>=1.2？

**Comment by lovychen** [comment]
when i up the tensorflow to 1.3，this code is ok。

**Comment by maxwill0102** [comment]
报错：argument --lstm_size:conflicting option string:--lstm_size
